In [41]:
from scipy.io import loadmat
import numpy as np
import pandas as pd
import scipy

In [2]:
dados = loadmat(r"C:\Users\jmlnn\Downloads\barra_6kv_condi_1.mat")
print(dados.keys())

dict_keys(['__header__', '__version__', '__globals__', 'absoluto'])


In [3]:
dados.values()

dict_values([b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Oct 25 09:54:30 2024', '1.0', [], array([[ 1.26266406e-01,  1.07125781e-01,  9.69695313e-02, ...,
         1.34078906e-01,  1.22164844e-01,  1.38571094e-01],
       [ 2.42780885e+01,  4.71812595e+01,  7.35990319e+01, ...,
         2.06046990e+02,  2.27669605e+02,  2.49815282e+02],
       [ 1.77637807e-02,  2.64073337e-02,  2.51448184e-02, ...,
         1.96421184e-02,  7.16884847e-03,  1.33674614e-02],
       ...,
       [ 1.77637807e-02,  1.18216758e-02,  2.71589820e-02, ...,
         1.23586275e-02,  8.76761038e-03,  2.09166100e-03],
       [ 1.93106094e-02, -9.40774910e-04,  7.01734600e-03, ...,
         3.61843832e-03, -8.24961128e-04,  6.32008617e-03],
       [ 1.77637807e-02,  4.52884681e-03,  1.70881640e-02, ...,
        -3.66505262e-03,  1.35638961e-02,  1.61864116e-02]])])

In [54]:
# Assuming 'dados' is a dictionary
df = pd.DataFrame(list(dados.values())[-1])
df

0          1          2           3           4           5   \
0     0.126266   0.107126   0.096970    0.111032    0.145798    0.116891   
1    24.278088  47.181260  73.599032  203.379397  223.703278  248.527455   
2     0.017764   0.026407   0.025145    0.009647    0.016724    0.022530   
3     0.025498   0.019115   0.023131    0.027237    0.011365    0.014176   
4     0.013123   0.017291   0.025145    0.011406    0.018063    0.000809   
..         ...        ...        ...         ...         ...         ...   
398   0.022404   0.020938   0.009032    0.021960    0.007346    0.019188   
399   0.005389   0.013645  -0.001039    0.018442    0.006007    0.012505   
400   0.017764   0.011822   0.027159    0.013165    0.015384    0.000809   
401   0.019311  -0.000941   0.007017    0.004370    0.016724    0.020859   
402   0.017764   0.004529   0.017088    0.030755    0.012705    0.019188   

            6          7           8           9   ...          42         43  \
0     0.103610   0.098727    0.150290    0.132712  ...    0.133102   0.108688   
1    32.626977  52.742221  214.536815  236.797458  ...  265.587097  20.008590   
2     0.017878   0.028654    0.009726    0.015429  ...    0.031525   0.018840   
3     0.014108   0.014806    0.009726    0.009543  ...    0.005112   0.018840   
4     0.025418   0.008871    0.012325    0.008071  ...    0.006580   0.011652   
..         ...        ...         ...         ...  ...         ...        ...   
398   0.014108   0.036567    0.012325    0.009543  ...    0.021254  -0.006318   
399   0.015993   0.024697    0.001929    0.013958  ...    0.005112   0.008058   
400   0.021648   0.026675    0.004528    0.011014  ...    0.006580  -0.002724   
401   0.012223   0.008871    0.011026    0.005127  ...    0.021254   0.015246   
402   0.008453   0.022719    0.013625    0.009543  ...    0.010982   0.013449   

            44         45         46         47         48          49  \
0     0.097165   0.099509   0.119235   0.105173   0.118454    0.134079   
1    40.848259  55.651693  28.259999  48.991628  76.367047  206.046990   
2     0.037155   0.008801   0.017173   0.019469   0.002447    0.019642   
3     0.015044   0.020578  -0.000845   0.015755   0.009042    0.022556   
4     0.004993   0.012727   0.022087   0.010184   0.022233    0.015272   
..         ...        ...        ...        ...        ...         ...   
398   0.025094   0.014689  -0.004121   0.019469   0.023882    0.010902   
399   0.013034   0.012727   0.007345   0.021327   0.018935    0.022556   
400   0.013034   0.012727   0.018811   0.006470   0.013989    0.012359   
401   0.013034   0.014689   0.013897   0.010184   0.010691    0.003618   
402   0.033135   0.014689   0.007345   0.026898   0.015638   -0.003665   

             50          51  
0      0.122165    0.138571  
1    227.669605  249.815282  
2      0.007169    0.013367  
3      0.021558    0.016186  
4      0.010366    0.013367  
..          ...         ...  
398    0.015163    0.013367  
399    0.011965    0.013367  
400    0.008768    0.002092  
401   -0.000825    0.006320  
402    0.013564    0.016186  

[403 rows x 52 columns]

In [56]:
# Criar a coluna de classe
df.loc['classe'] = ['positivo' if valor <= 180 else 'negativo' for valor in df.iloc[1, :]]

df

0         1          2           3           4           5   \
0        0.126266  0.107126    0.09697    0.111032    0.145798    0.116891   
1       24.278088  47.18126  73.599032  203.379397  223.703278  248.527455   
2        0.017764  0.026407   0.025145    0.009647    0.016724     0.02253   
3        0.025498  0.019115   0.023131    0.027237    0.011365    0.014176   
4        0.013123  0.017291   0.025145    0.011406    0.018063    0.000809   
...           ...       ...        ...         ...         ...         ...   
399      0.005389  0.013645  -0.001039    0.018442    0.006007    0.012505   
400      0.017764  0.011822   0.027159    0.013165    0.015384    0.000809   
401      0.019311 -0.000941   0.007017     0.00437    0.016724    0.020859   
402      0.017764  0.004529   0.017088    0.030755    0.012705    0.019188   
classe   positivo  positivo   positivo    negativo    negativo    negativo   

               6          7           8           9   ...          42  \
0         0.10361   0.098727     0.15029    0.132712  ...    0.133102   
1       32.626977  52.742221  214.536815  236.797458  ...  265.587097   
2        0.017878   0.028654    0.009726    0.015429  ...    0.031525   
3        0.014108   0.014806    0.009726    0.009543  ...    0.005112   
4        0.025418   0.008871    0.012325    0.008071  ...     0.00658   
...           ...        ...         ...         ...  ...         ...   
399      0.015993   0.024697    0.001929    0.013958  ...    0.005112   
400      0.021648   0.026675    0.004528    0.011014  ...     0.00658   
401      0.012223   0.008871    0.011026    0.005127  ...    0.021254   
402      0.008453   0.022719    0.013625    0.009543  ...    0.010982   
classe   positivo   positivo    negativo    negativo  ...    negativo   

              43         44         45         46         47         48  \
0       0.108688   0.097165   0.099509   0.119235   0.105173   0.118454   
1       20.00859  40.848259  55.651693  28.259999  48.991628  76.367047   
2        0.01884   0.037155   0.008801   0.017173   0.019469   0.002447   
3        0.01884   0.015044   0.020578  -0.000845   0.015755   0.009042   
4       0.011652   0.004993   0.012727   0.022087   0.010184   0.022233   
...          ...        ...        ...        ...        ...        ...   
399     0.008058   0.013034   0.012727   0.007345   0.021327   0.018935   
400    -0.002724   0.013034   0.012727   0.018811    0.00647   0.013989   
401     0.015246   0.013034   0.014689   0.013897   0.010184   0.010691   
402     0.013449   0.033135   0.014689   0.007345   0.026898   0.015638   
classe  positivo   positivo   positivo   positivo   positivo   positivo   

               49          50          51  
0        0.134079    0.122165    0.138571  
1       206.04699  227.669605  249.815282  
2        0.019642    0.007169    0.013367  
3        0.022556    0.021558    0.016186  
4        0.015272    0.010366    0.013367  
...           ...         ...         ...  
399      0.022556    0.011965    0.013367  
400      0.012359    0.008768    0.002092  
401      0.003618   -0.000825     0.00632  
402     -0.003665    0.013564    0.016186  
classe   negativo    negativo    negativo  

[404 rows x 52 columns]

In [62]:
# Filtrar os elementos positivos
semiciclo_positivo = df.loc[:, df.loc['classe'] == 'positivo'].to_numpy()[2:, :]
semiciclo_positivo

array([[0.017763780718102907, 0.02640733369367373, 0.025144818390237415,
        ..., 0.01717325927259408, 0.01946947358461561,
        0.00244689062527067],
       [0.025497924177015487, 0.019114504732577663, 0.023130654791870122,
        ..., -0.0008452309740750494, 0.01575534280273916,
        0.00904228308394656],
       [0.013123294642755383, 0.01729129749230363, 0.025144818390237415,
        ..., 0.022087392976231086, 0.010184146629924465,
        0.022233068001298338],
       ...,
       [0.019310609409885434, -0.000940774910436574,
        0.0070173460049319175, ..., 0.013897170136836064,
        0.010184146629924465, 0.010691131198615516],
       [0.017763780718102907, 0.0045288468103854935,
        0.017088163996768314, ..., 0.0073449918653200035,
        0.026897735148368514, 0.015637675542622447],
       ['positivo', 'positivo', 'positivo', ..., 'positivo', 'positivo',
        'positivo']], dtype=object)

In [63]:
semiciclo_negativo = df.loc[:, df.loc['classe'] == 'negativo'].to_numpy()[2:, :]
semiciclo_negativo

array([[0.009646709518431083, 0.01672373421771481, 0.02253025981261864,
        ..., 0.01964211840878407, 0.007168848466004703,
        0.01336746144215182],
       [0.027237354109577967, 0.011365280453233696, 0.014175817588794895,
        ..., 0.02255551478795561, 0.02155770573461333,
        0.016186411552317096],
       [0.011405773977545754, 0.018063347658835074,
        0.0008087100306768465, ..., 0.01527202384002681,
        0.010366372303473283, 0.01336746144215182],
       ...,
       [0.004369516141087012, 0.01672373421771481, 0.0208593713678539,
        ..., 0.0036184383233407225, -0.0008249611276667614,
        0.006320086166738613],
       [0.030755483027807336, 0.01270489389435396, 0.019188482923089136,
        ..., -0.0036650526245880777, 0.013563896140941892,
        0.016186411552317096],
       ['negativo', 'negativo', 'negativo', ..., 'negativo', 'negativo',
        'negativo']], dtype=object)

In [64]:
matrix = np.array(list(dados.values())[-1])
pulses = matrix[2:, :]
pulses

array([[ 0.01776378,  0.02640733,  0.02514482, ...,  0.01964212,
         0.00716885,  0.01336746],
       [ 0.02549792,  0.0191145 ,  0.02313065, ...,  0.02255551,
         0.02155771,  0.01618641],
       [ 0.01312329,  0.0172913 ,  0.02514482, ...,  0.01527202,
         0.01036637,  0.01336746],
       ...,
       [ 0.01776378,  0.01182168,  0.02715898, ...,  0.01235863,
         0.00876761,  0.00209166],
       [ 0.01931061, -0.00094077,  0.00701735, ...,  0.00361844,
        -0.00082496,  0.00632009],
       [ 0.01776378,  0.00452885,  0.01708816, ..., -0.00366505,
         0.0135639 ,  0.01618641]])

In [48]:
from numpy import ndarray

class SignalMetrics():

    def __init__(self, pulses: ndarray):
        """
        Inicializa a classe com um array de pulsos.

        Args:
            pulses(ndarray): Arrau NumPy contendo valores dos pulsos.
        """

        if not isinstance(pulses, ndarray): # Validações de entrada
            raise TypeError("Pulses devem ser um array NumPy.")
        if pulses.size == 0:
            raise ValueError("Pulses não pode ser vazio.")
        
        self.pulses = pulses
        self._peak_value = None # prefixo _ indica que são variáveis internas (convenção Python)
        self._rms = None
        self._avg_amplitude = None

    @property # permite acessar o método como se fosse um atributo (sem parênteses)
    def peak_value(self) -> float:
        """Calcula e retorna o valor de pico do sinal"""
        if self._peak_value is None:
            self._peak_value = np.max(np.abs(self.pulses), axis=1)
        return self._peak_value
    
    @property
    def rms(self) -> float:
        """Calcula e retorna o valor RMS do sinal"""
        if self._rms is None:
            self._rms = np.sqrt(np.mean(self.pulses**2, axis=1))
        return self._rms
    
    @property
    def avg_amplitude(self) -> float:
        """Calcula e retorna a amplitude média da matriz de pulsos"""
        if self._avg_amplitude is None:
            self._avg_amplitude = np.mean(np.abs(self.pulses))
        return self._avg_amplitude
    
    @property
    def sqrt_amplitude(self) -> float:
        """Calcula e retorna a raiz quadrada da amplitude média da matriz"""
        return np.sqrt(self.avg_amplitude)

    
    def get_crest_factor(self) -> float:
        """Calcula e retorna o fator de crista da matriz"""
        return self.peak_value / self.rms
    
    def get_clearance_factor(self) -> float:
        """Calcula e retorna o fator de liberação da matriz"""
        return self.peak_value / self.sqrt_amplitude
    
    def impulse_factor(self) -> float:
        """Calcula e retorna o fator de impulso da matriz"""
        return self.peak_value / self.avg_amplitude
    
    def shape_factor(self) -> float:
        """Calcula e retorna o fator de forma da matriz"""
        return self.rms / self.avg_amplitude
    
    def skewness(self) -> float:
        """Calcula e retorna a assimetria da matriz"""
        return scipy.stats.skew(self.pulses, axis=1)    

    def kurtosis(self) -> float:
        """Calcula e retorna a curtose da matriz"""
        return scipy.stats.kurtosis(self.pulses, axis=1)

In [ ]:
# Uso
pulses = [1, 2, 3, 4, 5]
rms = RMS(pulses)
print(rms.rms_value)  # Output: 3.3166247903554